/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wordle_bridge_GameBridge */

#ifndef _Included_com_wordle_bridge_GameBridge
#define _Included_com_wordle_bridge_GameBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wordle_bridge_GameBridge
 * Method:    getStatistics
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wordle_bridge_GameBridge_getStatistics
  (JNIEnv *, jobject);

/*
 * Class:     com_wordle_bridge_GameBridge
 * Method:    startGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wordle_bridge_GameBridge_startGame
  (JNIEnv *, jobject);

/*
 * Class:     com_wordle_bridge_GameBridge
 * Method:    processGuess
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_wordle_bridge_GameBridge_processGuess
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
